language: go

go:
  - 1.4.2
  - release
  - master

services:
  - postgresql

env:
  - RDS_DB_TEST_NAME=gymapptest
  - RDS_DB_USERNAME=testuser
  - RDS_DB_PASSWORD=slaptazodis
  - RDS_HOSTNAME=127.0.0.1

before_install:
  - go get github.com/tools/godep

install:
  - godep restore

before_script:
  - psql -c 'create database gymapptest;' -U postgres
  - psql -c "create user testuser with password 'slaptazodis';" -U postgres
  - psql -c "grant all privileges on database gymapptest to testuser;" -U postgres
  - go get github.com/revel/cmd/revel

script:
  - revel test gymapp testing
